export const API_HOST = process.env.PUBLIC_PLASMO_API_HOST;
export const ETH_GOERLI_ENDPOINT =
	process.env.PUBLIC_PLASMO_ETH_GOERLI_ENDPOINT || '';
export const POLYGON_MUMBAI_ENDPOINT =
	process.env.PUBLIC_PLASMO_POLYGON_MUMBAI_ENDPOINT || '';
